### ISSUE TITLE
Mobile issues on the Team page

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#9] opened 2022-03-24 23:01 UTC
I have found an issue while surfing the site with my smartphone. The team page seems broken, as you can see from the following video.

https://user-images.githubusercontent.com/14623986/160023200-ad416aff-745a-40b0-b80e-28aaa183ed99.MOV

I'll probably check the responsiveness of the site.

Model: iPhone XR
OS: iOS 15.3.1
Browser: Safari

**Comment by Wabri** [comment] 2022-03-25 06:37
I think the problem is not the mobile version, but the dark theme itself. 

![Screenshot_20220325-073420.png](https://user-images.githubusercontent.com/12409541/160067321-39666056-1f5b-4024-bf93-4c825765d6f5.png)

**Comment by nicpuppa** [comment] 2022-03-25 07:24
I think we have this problem because the text (name and description) does not change color, is always black (or dark grey)

**Comment by davideimola** [comment] 2022-03-25 07:56
Yes I have checked and you're right the problem is in the Dark theme.

To be honest, I don't like this thing in the lighter version too!

![image](https://user-images.githubusercontent.com/14623986/160078442-fd3176d9-e482-4c8c-a8b0-d1ab23101900.jpeg)

**Comment by Wabri** [comment] 2022-03-25 08:01
Mh yes you are right

**Comment by 404answernotfound** [comment] 2022-03-25 10:55
should be fixed, check pull requests

**Closed** 2022-03-25 11:34 UTC
Labels: bug
